import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Movies App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
